### ISSUE TITLE
Release and update packagist

### ISSUE THREAD

**Issue by marc-firebrand** [Rickycezar/laravel-jwt-impersonate#4]
Hi there,

Could you publish the latest changes in a release and sync it to Packagist please ?

Great module btw, saved me a lot of time doing it myself :)

Cheers

**Comment by marc-firebrand** [comment]
If you could merge #5 before doing so it would be ideal

**Comment by Rickycezar** [comment]
@marc-firebrand A new release has been created and packagist has been updated. Thanks for the fixes!
