### ISSUE TITLE
Support for PHP 8

### ISSUE THREAD

**Issue by vsergiu93** [Rickycezar/laravel-jwt-impersonate#7]
Could we get support for PHP 8 and Laravel 8?

**Comment by rebe73** [comment]
The only change needed is composer.json:
```
"require": {
      "php": "^7.1.3|^8.0",

```
code is php8 compatible. 
No rights to create pull request.

**Comment by Rickycezar** [comment]
@rebe73 Done.

**Comment by rebe73** [comment]
Hi again, please update packagist.

**Comment by brada1703** [comment]
Still getting an error with PHP8:

```
rickycezar/laravel-jwt-impersonate 1.3.0 requires php ^7.1.3 -> your php version (8.0.12) does not satisfy that requirement.
```

**Comment by Rickycezar** [comment]
@brada1703 You're using the 1.3.0 tag. 1.3.1 has this issue solved.
